name: File Check

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Current directory: $PWD"
          echo "Contents of the directory:"
          ls -al

      - name: Check if files exist
        run: |
          required_files=("README.md" "LICENSE" ".gitignore")
          for file in "${required_files[@]}"; do
            if [ ! -f "$PWD/$file" ]; then
              echo "Error: $file is missing"
              exit 1
            fi
          done
          echo "All required files are present."
